# Generated by Django 4.1.1 on 2022-10-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='locarion',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
