# Generated by Django 4.1.1 on 2022-10-31 08:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0002_rename_locarion_profile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='post_images')),
                ('caption', models.TextField(blank=True, max_length=80)),
                ('post_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('num_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
