# Generated by Django 4.1.1 on 2022-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0005_likepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
