# Generated by Django 4.1.1 on 2022-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0006_remove_profile_location_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
    ]
