# Generated by Django 4.1.1 on 2022-12-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0007_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_img',
            new_name='profileimg',
        ),
    ]
