# Generated by Django 4.1.1 on 2023-01-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0008_rename_profile_img_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=80)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prodesc', models.TextField(max_length=80)),
                ('pic', models.ImageField(upload_to='post_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
