# Generated by Django 4.1.1 on 2023-01-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0010_category_alter_host_info_host_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='info',
            new_name='description',
        ),
    ]
