# Generated by Django 4.1.1 on 2023-01-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0011_rename_info_host_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
