# Generated by Django 4.1.1 on 2023-02-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0013_alter_category_options_remove_host_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_name',
        ),
    ]
