# Generated by Django 4.1.1 on 2023-02-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0014_remove_host_host_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='is_full',
        ),
        migrations.RemoveField(
            model_name='host',
            name='price',
        ),
        migrations.AddField(
            model_name='host',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='host',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialspace.category'),
        ),
        migrations.AlterField(
            model_name='host',
            name='img',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
