# Generated by Django 4.1.1 on 2023-02-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0015_remove_host_is_full_remove_host_price_host_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='category',
        ),
        migrations.RemoveField(
            model_name='host',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='host',
            name='description',
        ),
        migrations.RemoveField(
            model_name='host',
            name='location',
        ),
        migrations.RemoveField(
            model_name='host',
            name='name',
        ),
    ]
