# Generated by Django 4.1.1 on 2023-02-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0017_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialspace.category'),
        ),
        migrations.AddField(
            model_name='host',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
