# Generated by Django 4.1.1 on 2023-03-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0022_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chat',
            new_name='conversation',
        ),
        migrations.AlterField(
            model_name='chat',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='socialspace.listing'),
        ),
    ]
