# Generated by Django 4.1.1 on 2023-03-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0023_rename_chat_chatmessage_conversation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='conversation',
            new_name='chat',
        ),
        migrations.AlterField(
            model_name='chat',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='socialspace.listing'),
        ),
    ]
